Page({
  data:{
    items:[
        {
          title:"网络API列表",
          content:[
              {
                sonTitle:'发起请求',
                apis:[{apititle:'wx.request',url:'./net/request/request'}]
              }
            ]
        },  
        {
          title:"媒体API列表",
          content:[
               {
                sonTitle:'图片',
                apis:[
                   {apititle:'wx.chooseImage',url:'./media/chooseImage/chooseImage'},
                   {apititle:'wx.previewImage',url:'./media/previewImage/previewImage'},
                   {apititle:'wx.getImageInfo',url:'./media/getImageInfo/getImageInfo'},
                ]
              },
              {
                sonTitle:'录音',
                apis:[
                   {apititle:'wx.startRecord',url:'./media/record/record'},
                   {apititle:'wx.stopRecord',url:'./media/record/record'}
                ]
              },
              {
                sonTitle:'音频播放控制',
                apis:[
                   {apititle:'wx.palyVoice',url:'./media/voice/voice'},
                   {apititle:'wx.pauseVoice',url:'./media/voice/voice'},
                   {apititle:'wx.stopVoice',url:'./media/voice/voice'}
                ]
              }, 
            ]
        },
         {
          title:"文件API列表",
          content:[
              {
                sonTitle:'文件',
                apis:[
                  {apititle:'文件',url:'./file/file/file'}
                ]
              }
            ]
        },  
        {
          title:"数据缓存API列表",
          content:[
              {
                sonTitle:'数据缓存文件',
                apis:[
                  {apititle:'数据缓存',url:'./storage/storage/storage'}
                ]
              }
            ]
        }, 
        {
          title:"位置API列表",
          content:[
              {
                sonTitle:'获取位置',
                apis:[
                  {apititle:'获取位置',url:'./location/location/location'}
                ]
              },
               {
                sonTitle:'查看位置',
                apis:[
                  {apititle:'查看位置',url:'./location/location/location'}
                ]
              },
               {
                sonTitle:'地图组件控制',
                apis:[
                  {apititle:'数据缓存',url:'./location/map/map'}
                ]
              }
            ]
        } ,
        {
          title:"设备API列表",
          content:[
              {
                sonTitle:'系统信息',
                apis:[
                  {apititle:'系统信息',url:'./device/systemInfo/systemInfo'}
                ]
              },
               {
                sonTitle:'网络状态',
                apis:[
                  {apititle:'wx.NetworkType',url:'./device/networkType/networkType'}
                ]
              },
               {
                sonTitle:'重力感应',
                apis:[
                  {apititle:'wx.onAccelerometerChange',url:'./device/accelerometer/accelerometer'}
                ]
              },
               {
                sonTitle:'罗盘',
                apis:[
                  {apititle:'wx.onCompassChange',url:'./device/compass/compass'}
                ]
              },
               {
                sonTitle:'拨打电话',
                apis:[
                  {apititle:'wx.makePhoneCall',url:'./device/makePhoneCall/makePhoneCall'}
                ]
              },
               {
                sonTitle:'扫描',
                apis:[
                  {apititle:'wx.scanCode',url:'./device/scanCode/scanCode'}
                ]
              }
            ]
        }  ,
        {
          title:"界面API列表",
          content:[
              {
                sonTitle:'交互反馈',
                apis:[
                  {apititle:'交互反馈',url:'./ui/feedback/feedback'}
                ]
              },
               {
                sonTitle:'设置导航条',
                apis:[
                  {apititle:'设置导航条',url:'./ui/navigationbar/navigationbar'}
                ]
              },
               {
                sonTitle:'导航',
                apis:[
                  {apititle:'导航',url:'./ui/navigation/navigation'}
                ]
              },
               {
                sonTitle:'动画',
                apis:[
                  {apititle:'动画',url:'./ui/animation/animation'}
                ]
              },
               {
                sonTitle:'下拉刷新',
                apis:[
                  {apititle:'下拉刷新',url:'./ui/refresh/refresh'}
                ]
              }
            ]
        } 
    ]
  },
  bindTap:function(event){
    console.log(event);
    wx.navigateTo({
      url: event.currentTarget.dataset['url']
    })
  }
})