Page({
  data:{
    items:[
        {
          id:0,
          title:"网络API列表",
          apis:[
              {apititle:'request',url:'xxxxx'}
            ]
        }
    ]
  },
  bindTap:function(event){
    console.log();
    wx.navigateTo({
      url: event.currentTarget.dataset['url']
    })
  }
})