Page({
  data:{
    items:[
        {
          id:0,
          title:"网络API列表",
          apis:[
              {apititle:'request',url:'./net/request/request'}
            ]
        },  
        {
          id:1,
          title:"媒体API列表",
          apis:[
               {apititle:'chooseImage',url:'./media/chooseImage/chooseImage'},
               {apititle:'previewImage',url:'./media/previewImage/previewImage'},
               {apititle:'getImageInfo',url:'./media/getImageInfo/getImageInfo'},
            ]
        }
    ]
  },
  bindTap:function(event){
    console.log(event);
    wx.navigateTo({
      url: event.currentTarget.dataset['url']
    })
  }
})